---
version: '3'
services:
  monitor:
    image: monitor:0.0.1-snapshot
    container_name: monitor
    depends_on:
      - broker
    volumes:
      - ./config-monitor.json:/go/src/app/config.json
      - ./monitor/test_files:/go/src/app/test_files
    restart: unless-stopped

  zookeeper:
    image: repo.tecgraf.puc-rio.br:18082/confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: repo.tecgraf.puc-rio.br:18082/confluentinc/cp-kafka:6.2.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Create topic NAME:PARTITION:REPLICAS
      KAFKA_CREATE_TOPICS: "job-info:1:1"
    restart: on-failure:5
  
  topic-creator:
    image: repo.tecgraf.puc-rio.br:18082/confluentinc/cp-kafka:6.2.1
    container_name: topic-creator
    restart: on-failure:5
    depends_on:
      - broker
    command: bash -c "
        kafka-topics --create --bootstrap-server broker:29092 --replication-factor 1 --partitions 3 --topic monitor_interesse ;
        kafka-topics --create --bootstrap-server broker:29092 --replication-factor 1 --partitions 1 --topic monitor_estado ;
        kafka-topics --create --bootstrap-server broker:29092 --replication-factor 1 --partitions 1 --topic job_info
      "

  akhq:
    image: repo.tecgraf.puc-rio.br:18082/tchiotludo/akhq
    container_name: akhq
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:29092"
    depends_on:
      - broker
