name: Go-Consumer

on:
  push:
    branches: [ main ]
    paths:
      - 'consumer/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'consumer/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd consumer && go build -v ./...

    - name: Test
      run: cd consumer && go test -v ./...